/**
 * Generates scripts/seed.sql from the legacy content/ markdown files plus
 * initial pages/projects rows. D1 can't be written from Node directly, so:
 *
 *   npm run seed
 *   npx wrangler d1 execute kuldeep-cc --local --file scripts/seed.sql
 *   npx wrangler d1 execute kuldeep-cc --remote --file scripts/seed.sql
 */
import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT = path.join(ROOT, "scripts", "seed.sql");

const q = (value: string) => `'${value.replace(/'/g, "''")}'`;

interface SeedPost {
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  tags: string[];
  publishedAt: string;
}

function readDir(dir: string, extraTags: string[] = []): SeedPost[] {
  const full = path.join(ROOT, "content", dir);
  if (!fs.existsSync(full)) return [];
  return fs
    .readdirSync(full)
    .filter((f) => f.endsWith(".md"))
    .map((file) => {
      const { data, content } = matter(fs.readFileSync(path.join(full, file), "utf8"));
      const tags: string[] = [...(data.tags ?? []), ...extraTags];
      return {
        slug: file.replace(/\.md$/, ""),
        title: data.title ?? file,
        excerpt: data.excerpt || data.description || "",
        content: content.trim(),
        tags,
        publishedAt: `${data.date}T09:00:00Z`,
      };
    });
}

const posts = [...readDir("blog"), ...readDir("case-studies", ["case-study"])];

const pages = [
  {
    slug: "home",
    // The home page renders this title as the giant statement headline.
    title: "Marketing, AI, and systems that compound.",
    content: [
      "I'm Kuldeep Paul — Head of Marketing at [Maxim AI](https://www.getmaxim.ai).",
      "",
      "I build AI-native marketing systems: automation, experimentation, and distribution that let small teams drive outsized growth. Data science background (MSc, University of Essex), 5+ years shipping product and marketing.",
      "",
      "This site is my journal — writing, projects, and what I'm learning along the way.",
    ].join("\n"),
  },
  {
    slug: "about",
    title: "About",
    content: [
      "I'm Kuldeep Paul, Head of Marketing at [Maxim AI](https://www.getmaxim.ai), where I work on AI-native growth: multi-agent content workflows, data-driven experimentation, and product narrative.",
      "",
      "Before this I spent 5+ years across product and marketing, and picked up an MSc in Applied Data Science from the University of Essex. I care about distribution, systems that compound, and writing things down.",
      "",
      "## Elsewhere",
      "",
      "- X: [@don_fedora](https://x.com/don_fedora)",
      "- LinkedIn: [kuldeep-paul](https://www.linkedin.com/in/kuldeep-paul/)",
      "- Email: [mail@kuldeep.cc](mailto:mail@kuldeep.cc)",
    ].join("\n"),
  },
];

const projects = [
  {
    title: "Maxim AI",
    url: "https://www.getmaxim.ai",
    description: "Evaluation and observability for AI agents. I lead marketing.",
    year: 2026,
    sort: 1,
  },
  {
    title: "CrawlDoctor",
    url: "https://kuldeep.cc/writing/crawldoctor-case-study",
    description: "AI-bot analytics and attribution for marketing teams. Built end to end.",
    year: 2026,
    sort: 2,
  },
];

const lines: string[] = ["-- Generated by scripts/seed-content.ts. Do not edit by hand."];

for (const p of posts) {
  lines.push(
    `INSERT OR REPLACE INTO posts (slug, title, excerpt, content_md, tags, status, published_at) VALUES (` +
      [q(p.slug), q(p.title), q(p.excerpt), q(p.content), q(JSON.stringify(p.tags)), "'published'", q(p.publishedAt)].join(", ") +
      `);`,
  );
}

for (const p of pages) {
  lines.push(
    `INSERT OR REPLACE INTO pages (slug, title, content_md) VALUES (${q(p.slug)}, ${q(p.title)}, ${q(p.content)});`,
  );
}

lines.push(`DELETE FROM projects;`);
for (const p of projects) {
  lines.push(
    `INSERT INTO projects (title, url, description, year, sort_order) VALUES (` +
      [q(p.title), q(p.url), q(p.description), String(p.year), String(p.sort)].join(", ") +
      `);`,
  );
}

fs.writeFileSync(OUT, lines.join("\n") + "\n");
console.log(`Wrote ${OUT}: ${posts.length} posts, ${pages.length} pages, ${projects.length} projects`);
